### ISSUE TITLE
Formatting on 4:3 monitor

### ISSUE THREAD

**Issue by Wavum** [WillEccles/startpage#2]
I think the formatting of the background isn't correct on a 4:3 monitor:

![01-02-_2017_16-27-20](https://cloud.githubusercontent.com/assets/15262665/22513156/939a653c-e89b-11e6-9761-6de3197fb1a2.png)

**Comment by WillEccles** [comment]
Interesting, I fixed that before. It was happening any time the height of the window is greater than a 16:9 ratio, and I fixed it for Safari. I will have to look into it for everything else. The issue is that on Safari, it's done way differently (the blur doesn't require any extra elements, just one CSS property and that's it), so to fix this issue on every other browser, I will have to put in a lot of work. Thanks for letting me know, I'll work this out 😄 

Gotta have something to do for the next couple days after classes!

**Comment by Wavum** [comment]
No problem :smile:

**Comment by WillEccles** [comment]
This issue is also one that will be hard for me to find the motivation to fix, since I have only 16:9, 16:10, and 21:9 displays, so I will never see this issue. The problem is that the width of the image has to be set manually (see [here](https://github.com/WillEccles/startpage/blob/gh-pages/index.css#L55)), so that I can remove the blur on the edges from the `filter` property. I might end up setting it to just something more than 100% (in %) so that it can always stay a percent width OR expand in order to fill the height. I'll figure it out.

Anyway, you mentioned your startpage in your pull request. Would you mind linking that here for me? 😄

**Comment by Wavum** [comment]
You could resize your browser to 4:3 format.

**Comment by WillEccles** [comment]
Yeah, that's what I am doing to test that (or I can use the responsive design tester, so that other tabs can remain normal).

**Comment by WillEccles** [comment]
Heh, I saw that 😉

**Comment by Wavum** [comment]
It works now

**Comment by WillEccles** [comment]
Issue from this fix: it doesn't work right on other size displays, and if you resize the window, the image doesn't follow correctly.

**Comment by WillEccles** [comment]
I'm gonna reopen this until I find a real fix for it, since it only temporarily fixed the issue and if you are looking at it on another size display, it cuts the image off at the right and the blurred portion doesn't scale right.

**Comment by Wavum** [comment]
I see...

**Comment by WillEccles** [comment]
So, the image behind the search box scales just right after your fix, but the background doesn't work quite right. Not entirely sure how your fix would have broken this, I'll look into it.

**Comment by WillEccles** [comment]
Ah, it appears it is because your fix [overwrites](https://github.com/WillEccles/startpage/pull/3/commits/2ead0042207b68a5fe46c4c19cee3eee6a3e2b6d#diff-bca1542f88ef8253c16b452e9ad09f98R15) the [previous setting](https://github.com/WillEccles/startpage/pull/3/commits/2ead0042207b68a5fe46c4c19cee3eee6a3e2b6d#diff-bca1542f88ef8253c16b452e9ad09f98R9) for `background-size`, which I forgot that I changed.
